// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx9lnegwo1C2L-VpMqUm33Wi5Z9MHXkek',
    appId: '1:739108795965:web:186656b89c8c00fd81dc54',
    messagingSenderId: '739108795965',
    projectId: 'flutter-iti-firebase',
    authDomain: 'flutter-iti-firebase.firebaseapp.com',
    storageBucket: 'flutter-iti-firebase.firebasestorage.app',
    measurementId: 'G-5KE1551ZQH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFCPspnDHJEDRoL7aL6E8j6V5HHstSXko',
    appId: '1:739108795965:android:b14018da7c291acc81dc54',
    messagingSenderId: '739108795965',
    projectId: 'flutter-iti-firebase',
    storageBucket: 'flutter-iti-firebase.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPLlMARrPVuJdCds1bKrcOqycQODIO-pE',
    appId: '1:739108795965:ios:0b99dbb063a6b23681dc54',
    messagingSenderId: '739108795965',
    projectId: 'flutter-iti-firebase',
    storageBucket: 'flutter-iti-firebase.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPLlMARrPVuJdCds1bKrcOqycQODIO-pE',
    appId: '1:739108795965:ios:0b99dbb063a6b23681dc54',
    messagingSenderId: '739108795965',
    projectId: 'flutter-iti-firebase',
    storageBucket: 'flutter-iti-firebase.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCx9lnegwo1C2L-VpMqUm33Wi5Z9MHXkek',
    appId: '1:739108795965:web:eb04aa7f56b25a5c81dc54',
    messagingSenderId: '739108795965',
    projectId: 'flutter-iti-firebase',
    authDomain: 'flutter-iti-firebase.firebaseapp.com',
    storageBucket: 'flutter-iti-firebase.firebasestorage.app',
    measurementId: 'G-KKJME746JK',
  );
}
